import { ref } from "vue";
export const girlfriends = [
  {
    url: "/big headshots/HeadshotHakari.png",
    num: "1",
    char: "haka",
    name: "Hanazono Hakari",
  },
  {
    url: "/big headshots/HeadshotKarane.png",
    num: "1",
    char: "kara",
    name: "Inda Karane",
  },
  {
    url: "/big headshots/HeadshotShizuka.png",
    num: "3",
    char: "shizu",
    name: "Yoshimoto Shizuka",
  },
  {
    url: "/big headshots/HeadshotNano.png",
    num: "4",
    char: "nano",
    name: "Eiai Nano",
  },
  {
    url: "/big headshots/HeadshotKusuri.png",
    num: "5",
    char: "kusu",
    name: "Yakuzen Kusuri",
  },
  {
    url: "/big headshots/HeadshotHakari.png",
    num: "6",
    char: "haha",
    name: "Hanazono Hahari",
  },
  {
    url: "/big headshots/HeadshotKurumi.png",
    num: "7",
    char: "kuru",
    name: "Haraga Kurumi",
  },
  {
    url: "/big headshots/HeadshotMei.png",
    num: "8",
    char: "mei",
    name: "Meido Mei",
  },
  {
    url: "/big headshots/HeadshotIku.png",
    num: "9",
    char: "iku",
    name: "Sutou Iku",
  },
  {
    url: "/big headshots/HeadshotMimimi.png",
    num: "10",
    char: "mimi",
    name: "Utsukushisugi Mimimi",
  },
  {
    url: "/big headshots/HeadshotMeme.png",
    num: "11",
    char: "meme",
    name: "Kakure Meme",
  },
  {
    url: "/big headshots/HeadshotChiyo.png",
    num: "12",
    char: "chiyo",
    name: "Iin Chiyo",
  },
  {
    url: "/big headshots/HeadshotNaddy.png",
    num: "13",
    char: "naddy",
    name: "Naddy (Yamato Nadeshiko)",
  },
  {
    url: "/big headshots/HeadshotYamame.png",
    num: "14",
    char: "yama",
    name: "Yasashiki Yamame",
  },
  {
    url: "/big headshots/HeadshotMomiji.png",
    num: "15",
    char: "momi",
    name: "Momi Momiji",
  },
  {
    url: "/big headshots/HeadshotYaku.png",
    num: "16",
    char: "yaku",
    name: "Yakuzen Yaku",
  },
  {
    url: "/big headshots/HeadshotKishika.png",
    num: "17",
    char: "kishi",
    name: "Torotoro Kishika",
  },
  {
    url: "/big headshots/HeadshotAhko.png",
    num: "18",
    char: "ahko",
    name: "Kedarui 'Ahko' Aashii",
  },
  {
    url: "/big headshots/HeadshotUto.png",
    num: "19",
    char: "uto",
    name: "Nakaji Uto",
  },
  {
    url: "/big headshots/HeadshotMai.png",
    num: "20",
    char: "mai",
    name: "Meido Mai",
  },
  {
    url: "/big headshots/HeadshotMomoha.png",
    num: "21",
    char: "moha",
    name: "Bonnouji Momoha",
  },
  {
    url: "/big headshots/HeadshotRin.png",
    num: "22",
    char: "rin",
    name: "Baio Rin",
  },
  {
    url: "/big headshots/HeadshotSuu.png",
    num: "23",
    char: "su",
    name: "Hifumi Suu",
  },
  {
    url: "/big headshots/HeadshotEira.png",
    num: "24",
    char: "eira",
    name: "Kaho Eira",
  },
  {
    url: "/big headshots/HeadshotTama.png",
    num: "25",
    char: "tama",
    name: "Nekonari Tama",
  },
  {
    url: "/big headshots/HeadshotHimeka.png",
    num: "26",
    char: "kiki",
    name: "Saiki 'Kiki' Himeka",
  },
  {
    url: "/big headshots/HeadshotMatsuri.png",
    num: "27",
    char: "matsu",
    name: "Dei Matsuri",
  },
  {
    url: "/big headshots/HeadshotShiina.png",
    num: "28",
    char: "usa",
    name: "Usami 'Usa-chan' Shiina",
  },
  {
    url: "/big headshots/HeadshotMeru.png",
    num: "29",
    char: "meru",
    name: "Zetsubouda Meru",
  },
  {
    url: "/big headshots/HeadshotSaki.png",
    num: "30",
    char: "saki",
    name: "Tomogara Saki",
  },
  {
    url: "/big headshots/HeadshotNemu.png",
    num: "31",
    char: "nemu",
    name: "Nemui Nemu",
  },
  {
    url: "/big headshots/HeadshotHasuha.png",
    num: "32",
    char: "hasu",
    name: "Hasu Hasuha",
  },
  //{ url: "/big headshots/Headshot--.png", num: "33", chars: "Morikita Kimari" },
];
